name: zis_b
description: Variant B ZIS App

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/zis_0071.jpg
    - images/zis_1498.jpg
    - images/zis_2567_130.jpg
    - images/zis_30843.jpg
    - images/zis_9861.jpg
    - images/zis_Upper-School.jpg
