name: zpg_a
description: Variant A ZIS Project Green App

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/a.png
    - images/b.png
    - images/c.png
    - images/d.png
    - images/e.png
